lightning:
  url: "replaceme"
  macaroon_path: "replaceme"
  tls_path: "replaceme"

data_sig:
  tlv_key: 293345193 # replace with desired TLV key to insert DataSig structure into

data_struct:
  tlv_key: 293345191 # replace with desired TLV key to insert DataStruct structure into
  max_fragment_size: 1024 # replace with desired maximum size per fragment
  min_fragment_size: 512 # replace with desired minimum size per fragment
