lightning:
  url: "replaceme"
  macaroon_path: "replaceme"
  tls_path: "replaceme"

data_sig:
  tlv_key: 293345193 # replace with desired TLV key to insert DataSig structure into

data_struct:
  # WARNING:  Transmitting data bigger than the default maximum size of 5MB can burn
  #           big amounts of sats. Experiment at your own risk.
  max_data_size: 5242880 # Maximum allowed size for data to be transmitted.
  tlv_key: 293345191 # replace with desired TLV key to insert DataStruct structure into
  fragment_size: 1024 # replace with desired maximum size per fragment
  fragment_workers: 10 #replace with desired number of workers to handle RPC calls towards LND